#### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
# 2D and 3D
b = np.array([[1,2,3],[3,4,5]])
b


array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [10]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [13]:
# np.ones and np.zeros
o = np.ones((3,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
z = np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# np.random
np.random.random((3,4))

array([[9.86363375e-01, 7.40234850e-01, 7.63682635e-01, 5.26270388e-01],
       [6.53029867e-01, 5.99736964e-01, 2.21112171e-02, 8.35967209e-01],
       [7.36074337e-01, 6.77467683e-01, 3.17021187e-04, 4.20037952e-01]])

In [18]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [19]:
# np.identity
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])