### Array Attributes

In [2]:
import numpy as np

In [4]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12,dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [4]:
# ndim
a1.ndim   # ndim it tells the number of dimensions

1

In [5]:
# shape
print(a3.shape)
a3     # It tells how many rows and columns are there


(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
# Size
a1.size   # It tells the number of items in the array

10

In [7]:
# itemsize
a1.itemsize  # Tells the size occupied in the memory


4

In [8]:
# dtype (it tells the data type)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)   # used to change the data type (or cast) of elements in an existing array, returning a new array with the specified

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operation

In [10]:
aa1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
# Scalar Operation
# arithmetic operator

print(a2 ** 2)

[[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]]


In [32]:
# Relational operator
a2 > 15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [33]:
print(a2 == 15)


[[False False False False]
 [False False False False]
 [False False False False]]


In [36]:
# vector operation
# arithmetic
a2 * a2

array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.]])