
### Array Function

In [31]:

import numpy as np

In [33]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[35., 41., 35.],
       [95., 27., 64.],
       [ 8., 60., 34.]])

In [11]:
 # max/min/sum/prod
# 0 -> column and 1 -> rows
print(np.max(a1, axis= 1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

[91. 54. 65.]
5.0
436.0
124739578577250.0


In [30]:
# mean/median/std/var
np.median(a1, axis= 1)

array([39., 54., 76.])

In [31]:
# Trigonometric function
np.sin(a1)

array([[ 0.96379539, -0.66363388, -0.99388865],
       [-0.55878905,  0.27090579,  0.77389068],
       [ 0.56610764, -0.11478481,  0.73319032]])

In [9]:
# Dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [26]:
# log and exponent
(np.log(a1))


array([[3.8918203 , 4.51085951, 4.44265126],
       [3.04452244, 3.98898405, 3.8501476 ],
       [1.60943791, 2.94443898, 4.17438727]])

In [37]:
#round/floor/ceil
np.round(np.random.random((2,3))* 100)    # Round: It returns to the nearest integer

array([[11., 77.,  5.],
       [17., 65., 83.]])

In [4]:
np.floor(np.random.random((2,3)) * 100)

array([[63., 74., 85.],
       [91., 28., 52.]])

### Indexing and Slicing

In [23]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
# a3 = np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
print(a1[-1])

9


In [11]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
print(a2[1,2])    # first tells its rows that in which row it exist and then tell its column

6


In [16]:
print(a2[2,3])

11


In [18]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
print(a3[1,0,1])

5


In [22]:
print(a3[0,0,0])

0


### Slicing

In [23]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a1[2:5]

array([2, 3, 4])

In [25]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a2[0,:]

array([0, 1, 2, 3])

In [27]:
a2[:,0]

array([0, 4, 8])

In [30]:
print(a2[1:,1:3])

[[ 5  6]
 [ 9 10]]


In [32]:
print(a2[1:,0:2])

[[4 5]
 [8 9]]


In [34]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
print(a2[::2,::3])

[[ 0  3]
 [ 8 11]]


In [47]:
print(a2[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [50]:
print(a2[1,::3])

[4 7]


In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
print(a2[:2,1:])

[[1 2 3]
 [5 6 7]]


In [2]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
print(a3[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [10]:
print(a3[0,1,:])

[3 4 5]


In [14]:
print(a3[1,:,1])

[10 13 16]


In [18]:
print(a3[2,1:,1:])

[[22 23]
 [25 26]]


In [19]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
print(a3[0::2,0,0::2])

[[ 0  2]
 [18 20]]


### Iterating

In [24]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [26]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
for i in a2:   # it print one row at a time
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [28]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
for i in a3:
    print(i)      # it print one 2d array at a time

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [4]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [5]:
# Reshape

In [12]:
# Transpose ---> convert row into column
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [14]:
# ravel ---> which type of array it is 2d or 3d ravel convert it into 1d
a2.ravel()



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [16]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [19]:
# vertical stacking
np.vstack((a4,a5))  # shape must be same to do stacking

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [22]:
# horizontal split
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [29]:
# vertical split
print(np.vsplit(a4,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
